pretrained_sd_path: "pretrained_models/stable-diffusion-v1-5"
pretrained_clip_path: "pretrained_models/clip-vit-base-patch32"
pretrained_GE_path: "pretrained_models/GS-Extractor.ckpt"
pretrained_LD_path: "pretrained_models/L-Diffuser.ckpt"

savename: null

fusion_blocks: "full"


seed:           [42]
steps:          25

inference_config: "configs/inference/inference.yaml"
size: 256
L:    16
S:    1 
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false


