output_dir: "output"
pretrained_model_path: PATH To Your Pretrained Stable-Diffusion-Model
clip_model_path: PATH To Your Pretrained CLIP-Model

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

description: "### Train Info: train stage 1: GS-Extractor ###"

train_data:
  video_folder: PATH To Your Video Datset
  sample_size:  512
  clip_model_path: PATH To Your Pretrained CLIP-Model

fusion_blocks: "full"

learning_rate:    1.e-5
train_batch_size: 2

max_train_epoch:      -1
max_train_steps:      110000
checkpointing_steps:  5000
gradient_accumulation_steps: 4

global_seed: 42
mixed_precision_training: False
enable_xformers_memory_efficient_attention: True

is_debug: False
